//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Math_Collection_Interface.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Math_Collection_Interface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Operations
        ///- Degrees To Radians
        ///
        ///Vector Operations
        ///- Dot Product
        ///- Magnitude
        ///- Addition With Vector
        ///- Subtraction With Vector
        ///- Multiplication With Vector
        ///- Multiplication With Scalar
        ///
        ///Matrix Operations
        ///- Transpose Matrix
        ///- Multiply With Scalar
        ///- Multiply With Vector
        ///- Multiply With Matrix
        ///- Potentiate Matrix
        ///- Lower Left Pyramid Form
        ///- Upper Right Pyramid Form
        ///
        ///Analysis Operations
        ///- Derivation of a Function.
        /// </summary>
        internal static string Functions {
            get {
                return ResourceManager.GetString("Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix 2x2
        ///Matrix 2x3
        ///Matrix 2x4
        ///Matrix 2x5
        ///Matrix 3x2
        ///Matrix 3x3
        ///Matrix 3x4
        ///Matrix 3x5
        ///Matrix 4x2
        ///Matrix 4x3
        ///Matrix 4x4
        ///Matrix 4x5
        ///Matrix 5x2
        ///Matrix 5x3
        ///Matrix 5x4
        ///Matrix 5x5.
        /// </summary>
        internal static string Matrix_Combo_Box_Values {
            get {
                return ResourceManager.GetString("Matrix_Combo_Box_Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vector 1x2
        ///Vector 1x3
        ///Vector 1x4
        ///Vector 1x5.
        /// </summary>
        internal static string Vector_Combo_Box_Values {
            get {
                return ResourceManager.GetString("Vector_Combo_Box_Values", resourceCulture);
            }
        }
    }
}
